#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn prettify && yarn lint && yarn update-po && yarn test

if command -v snyk >/dev/null 2>&1; then
  snyk auth
  snyk test
else
  echo "snyk not found. Install it to run snyk auth/test."
fi
